### ISSUE TITLE
hook_config_info cleanup

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/coder_upgrade#28] opened 2020-08-21 20:31 UTC
Example from a recent port, `hook_config_info` comes out like this:

```
/**
 * Implements hook_config_info().
 */
function userprotect_config_info() {
  $prefixes['userprotect.settings'] = array(
    'label' => t('Module name settings'),
    'group' => t('Configuration'),
  );
}
```

Ideally:

 - Label includes actual module name
 - There is a `return $prefixes;` at the end of the function

**Comment by olafgrabienski** [comment] 2020-08-24 15:19
I confirm the missing `return $prefixes;`. Happened to me when I ported the Tocbot module running Coder upgrade.

By the time I noticed the issue, I wasn't 100% sure if I somehow made a mistake by myself. See https://github.com/backdrop/backdrop-issues/issues/4186#issuecomment-562168627.

**Comment by klonos** [comment] 2020-12-17 22:29
Not sure why the `return $prefixes;` bit is not being added 🤷  ...I see that there's code to do just that: https://github.com/backdrop-contrib/coder_upgrade/blob/1.x-1.x/coder_upgrade.module#L168

**Comment by bugfolder** [comment] 2021-02-21 15:59
I'd noticed this, and this morning tracked it down.

In https://github.com/backdrop-contrib/coder_upgrade/blob/1.x-1.x/coder_upgrade.module#L170-L174, there's these lines:
```
  $body_content = $editor->textToStatements(implode("\n", $strings))->getElement();

  $body = new PGPBody();
  $body->insertLast($body_content);
  $function->body = $body;
```

The problem is that the call to `getElement()` only takes the first statement in the `hook_config_info()` body, which is the `$prefixes = ...` assignment. Everything after that (the `return $prefixes`) is dropped.

The solution is to replace those lines of code with this statement:

```
  $function->body = $editor->textToStatements(implode("\n", $strings));
```

I've verified that this works, giving the `hook_config_info()` implementation with the proper return value.

I'll prepare a PR.

**Comment by bugfolder** [comment] 2021-02-21 18:56
[PR](https://github.com/backdrop-contrib/coder_upgrade/pull/32).

Something puzzling seems to be going on with the PHP 5.3 test, not related to the module code.

**Comment by indigoxela** [comment] 2021-02-22 07:18
There's some deeper problem with the tests - unrelated to this PR:

1. PHP 5.3 is supported only on Precise. (https://travis-ci.com/github/backdrop-contrib/coder_upgrade/jobs/484900072)
2. rbenv: version `5.5' not installed - The command "phpenv global 5.5" failed and exited with 1 during . (https://travis-ci.com/github/backdrop-contrib/coder_upgrade/jobs/484900070)

The file travis.yml is seven years old and I suspect, that the tests already fail for quite some time. Again, unrelated to this PR.

I have a functioning travis.yml with i18n. Open an extra issue for the tests and we can fix it with some copy-paste from there. :wink:

**Comment by bugfolder** [comment] 2021-03-15 00:42
This issue (missing `return $prefixes`) was fixed by PR https://github.com/backdrop-contrib/coder_upgrade/pull/32.

**Closed as completed by bugfolder** 2021-03-15 00:42 UTC
