### ISSUE TITLE
Broken Page | admin/config/development/coder-upgrade/settings

### ISSUE THREAD

**Issue by rayjamesdev** [backdrop-contrib/coder_upgrade#80] opened 2023-02-09 23:00 UTC
After installing the module, on the /admin/modules page, when I click on CONFIGURE for that module, I get the following error the page located at admin/config/development/coder-upgrade/settings:
Error
set_exception_handler(): Argument #1 ($callback) must be a valid callback or null, class PGPParser does not have a method "exception_handler"

I have included screenshots as well.
Thanks
![error_when_clicked](https://user-images.githubusercontent.com/51662089/217958026-06fcae4e-1d1d-47f0-94f1-5347769a8252.jpg)
![settings_error](https://user-images.githubusercontent.com/51662089/217958040-3bbdd006-d36d-475d-9ee5-a9bff09ebaf5.jpg)

**Comment by bugfolder** [comment] 2023-02-09 23:11
Hmm, this looks a lot like what was reported here:

https://github.com/backdrop-contrib/coder_upgrade/issues/78#issuecomment-1355166329

Can you check the watchdog log at path `admin/reports/dblog`, which should also give the fine and line number where that error is happening?

**Comment by rayjamesdev** [comment] 2023-02-09 23:13
More info:

Fresh install of : Backdrop 1.24.0
Windows 11
Xampp version 8.1.12
PHP Version: 8.1.12
MySQL Version: 8.0.32 - MySQL Community Server - GPL

WATCHDOG RESULTS: 
TypeError: set_exception_handler(): Argument #1 ($callback) must be a valid callback or null, class PGPParser does not have a method "exception_handler" in set_exception_handler() (line 107 of D:\xampp8.1.12\htdocs\mysite\site\modules\Contrib\coder_upgrade\grammar_parser\parser.inc).

Thanks for your time.  I'm also not able to convert a module, but I will post that issue separately. thx

**Comment by bugfolder** [comment] 2023-02-10 00:01
Some testing confirms that this error happens reproducibly on PHP 8.1 and not on PHP 7.4 or less. Also happens on PHP 8.0.

**Comment by docwilmot** [comment] 2023-02-16 19:24
@rayjamesdev could you please test that the latest code fixes this issue?

**Comment by rayjamesdev** [comment] 2023-02-16 19:47
Hi, my apologies. I trashed my entire 8.1 setup and am using 7.2 for development.  I no longer have the means of testing/using 8.1

**Comment by bugfolder** [comment] 2023-04-18 14:49
OK. Closing, since it appears the fix for https://github.com/backdrop-contrib/coder_upgrade/issues/78 addressed the problem.

**Closed as completed by bugfolder** 2023-04-18 14:49 UTC
