### ISSUE TITLE
Empty hook_update_1000() function

### ISSUE THREAD

**Issue by oadaeh** [backdrop-contrib/coder_upgrade#29] opened 2020-09-23 01:36 UTC
What is the reason for creating an empty hook_update_1000() function? I could not find anything about it in the code or Backdrop developer documentation.

**Comment by docwilmot** [comment] 2020-09-23 04:44
Edit: answered the wrong question. Thats probably just an oversight in the coding.

**Comment by VasasA** [comment] 2020-09-23 08:48
You need hook_update_1000() function, if you have to migrate the variables to config. You have to complete the empty function. Read the section "Create an upgrade path" in this description: https://api.backdropcms.org/converting-modules-from-drupal

**Comment by oadaeh** [comment] 2020-09-23 14:26
Thanks @docwilmot. I might take a look and see if I can create a PR to fix that.

Thanks @VasasA for the feedback. I did see that, but the function in the module I was upgrading is empty, and I was wondering if that was intentional for some reason I could not locate.

**Comment by docwilmot** [comment] 2020-09-23 15:44
I suspect maybe if a module doesnt have any `variable_x` calls, we may get that empty function. Or maybe `variable_x` calls but none were convertible to config (unable to match).

**Comment by bugfolder** [comment] 2021-05-25 21:30
There have been several updates since this comment was originally posted. The problem may (or may not) be fixed by past updates. Can you provide a minimal example that results in an empty `hook_update_1000()` function?

**Comment by bugfolder** [comment] 2021-12-18 23:07
I've been unable to reproduce this behavior. I've tried a module lacking any `variable_x` functions, and a module with a `variable_get()` whose name was unmatchable.

Since there have been no further reports of the behavior and no examples to reproduce it, I'm closing the issue.

**Closed as completed by bugfolder** 2021-12-18 23:07 UTC
